// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRC.Data;

#nullable disable

namespace GoRide.IdentityAuth.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828213931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SRC.Entities.DriverProfile", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("LicenseExpiry")
                        .HasColumnType("date")
                        .HasColumnName("license_expiry");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("license_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_make");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_plate");

                    b.Property<string>("VehicleTypeCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_type_code");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verified_at");

                    b.HasKey("DriverId");

                    b.ToTable("driverprofiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
