// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRC.Data;

#nullable disable

namespace GoRide.IdentityAuth.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902191659_AddDriverDocuments")]
    partial class AddDriverDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SRC.Entities.DriverDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("document_number");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("driver_id");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("document_type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_documents_driver_type");

                    b.ToTable("driver_documents", (string)null);
                });

            modelBuilder.Entity("SRC.Entities.DriverProfile", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("LicenseExpiry")
                        .HasColumnType("date")
                        .HasColumnName("license_expiry");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("license_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_make");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_plate");

                    b.Property<string>("VehicleTypeCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_type_code");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verified_at");

                    b.HasKey("DriverId");

                    b.ToTable("driverprofiles", (string)null);
                });

            modelBuilder.Entity("SRC.Entities.UserAccount", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("UserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_user_accounts_status");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("SRC.Entities.DriverDocument", b =>
                {
                    b.HasOne("SRC.Entities.DriverProfile", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
